version: "3.8"
networks:
  example-microservices:
    driver: bridge
services:

  authentication-db:
    extends:
      file: ./common/common-services.yaml
      service: authentication-db
    volumes:
     - "authentication-db:/var/lib/mysql"
    networks:
      - example-microservices

  feed-db:
    extends:
      file: ./common/common-services.yaml
      service: feed-db
    volumes:
     - "feed-db:/var/lib/mysql"
    networks:
      - example-microservices

  redis-cache:
    extends:
      file: ./common/common-services.yaml
      service: redis-cache
    volumes:
     - "redis_data:/data"
    networks:
      - example-microservices

  redis-commander:
    extends:
      file: ./common/common-services.yaml
      service: redis-commander
    networks:
      - example-microservices
  
  authentication:
    build:
      context: ./authentication
      dockerfile: authentication.dockerfile
    image: authentication
    container_name: authentication
    ports:
      - "4001:4001"
    platform: linux/x86_64
    env_file: 
     - authentication/.env
    environment:
      PORT: 4001
      NODE_ENV: production
      MYSQL_HOST: authentication-db
      MYSQL_PORT: 3306
      MYSQL_USER: user123456
      MYSQL_PASS: 123456
      MYSQL_NAME: authentication
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      REDIS_TTL: 600
      REDIS_USERNAME: "redis-master"
      REDIS_PASSWORD: "123456"
      JWT_SECRET: "secret123456"
      REFRESH_JWT_SECRET: "secret123456"
      EXPIRES_IN: "5m"
    depends_on:
      - authentication-db
    networks:
      - example-microservices

  feed:
    build:
      context: ./feed
      dockerfile: feed.dockerfile
    image: feed
    container_name: feed
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      MYSQL_HOST: feed-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: 123456
      MYSQL_NAME: feed
      NODE_ENV: production
    platform: linux/x86_64
    depends_on:
      - feed-db
      - authentication
    networks:
      - example-microservices

  ui:
    build:
      context: ./ui
      dockerfile: ui.dockerfile
    image: ui
    container_name: ui
    ports:
      - "4003:4003"
    environment:
      NODE_ENV: production
      PORT: 4003
      AUTHENTICATION_UI: "authentication@http://localhost:81/api/authentication/static/remoteEntry.js"
      FEED_UI: "feed@http://localhost:81/api/feed/static/remoteEntry.js"
    platform: linux/x86_64
    depends_on:
      - authentication
      - feed
    networks:
      - example-microservices
  
  api-gateway:
    extends:
      file: ./common/common-services.yaml
      service: api-gateway
    depends_on:
      - authentication
      - feed
      - ui
    networks:
      - example-microservices
        
volumes:
  redis_data:
  authentication-db:
    driver:
      local
  feed-db:
    driver:
      local