version: "3.8"
networks:
  example-microservices:
    driver: bridge
services:

  db:
    extends:
      file: ./common/common-services.yaml
      service: db
    volumes:
     - "db:/var/lib/mysql"
    networks:
      - example-microservices

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    image: authentication
    container_name: authentication
    ports:
      - "4001:4001"
      - "8001:8001"
    volumes:
      - ./authentication:/authentication
    env_file: ./authentication/.env
    depends_on:
      - db
    networks:
      - example-microservices

  feed:
    build:
      context: ./feed
      dockerfile: Dockerfile
    image: feed
    container_name: feed
    ports:
      - "4002:4002"
      - "8002:8002"
    volumes:
      - ./feed:/feed
    env_file: ./feed/.env
    depends_on:
      - db
    networks:
      - example-microservices

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: ui
    container_name: ui
    ports:
      - "4003:4003"
      - "8003:8003"
    volumes:
      - ./ui:/ui
    env_file: ./ui/.env
    depends_on:
      - authentication
      - feed
    networks:
      - example-microservices
  
  api-gateway:
    extends:
      file: ./common/common-services.yaml
      service: api-gateway
    networks:
      - example-microservices
        
volumes:
  redis_data:
  db:
    driver:
      local