apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-jwt-keys
type: Opaque
data:
  JWT_SECRET: {{ .Values.JWT_SECRET | b64enc }}
  REFRESH_JWT_SECRET: {{ .Values.REFRESH_JWT_SECRET | b64enc }}
