namespace: default
appName: feed
replicaCount: 1

image:
  repository: mahmudulazamshohan/feed
  tag: "main-abc35b1"

PORT: 4002
servicePort: 82
protocalType: http

NODE_ENV: production

serviceType: NodePort

ingressHost: localhost

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

mysql:
  enabled: true
  auth:
    username: "user123456"
    password: "123456"
    database: "feed"
    rootPassword: "feed"
  primary:
    persistence:
      enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

MYSQL_HOST: feed-mysql
MYSQL_PORT: 3306
MYSQL_USER: user123456
MYSQL_PASS: 123456
MYSQL_NAME: feed