namespace: default
appName: example-microservices
replicaCount: 2

image:
  repository: mahmudulazamshohan/authentication
  tag: "2.5"

containerPort: 4001
servicePort: 80
protocalType: http

configMap:
  name: example-configmap-v1

serviceType: NodePort

ingressHost: localhost

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

MYSQL_HOST: db
MYSQL_PORT: 3306
MYSQL_USER: root
MYSQL_PASS: 123456
MYSQL_NAME: example_db
