
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  label:
    app: {{ .Values.appName }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.PORT }}
          env:
           - name: PORT
             value: "{{ .Values.PORT }}"
           - name: AUTHENTICATION_UI
             value: "{{ .Values.AUTHENTICATION_UI }}"
           - name: FEED_UI
             value: "{{ .Values.FEED_UI }}"
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
