namespace: default
appName: authentication
replicaCount: 1

image:
  repository: mahmudulazamshohan/authentication
  tag: "main-6302040"

PORT: 4001
servicePort: 81
protocalType: http
NODE_ENV: production

configMap:
  name: example-configmap-v2

serviceType: NodePort

ingressHost: localhost

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

mysql:
  enabled: true
  auth:
    username: "user123456"
    password: "123456"
    database: "authentication"
    rootPassword: "authentication"
  primary:
    persistence:
      enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"


redis:
  master:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  replica:
    replicaCount: 0
    enabled: false
  usePassword: true
  password: 123456
  service:
    type: ClusterIP
  metrics:
    enabled: true

MYSQL_HOST: authentication-mysql
MYSQL_PORT: 3306
MYSQL_USER: user123456
MYSQL_PASS: 123456
MYSQL_NAME: authentication
REDIS_HOST: redis-master
REDIS_PORT: 6379
REDIS_TTL: 600
REDIS_USERNAME: "redis-master"
REDIS_PASSWORD: "123456"
JWT_SECRET: 6C4mM1Q4sHsxydgthxw_mAGVP_qNyv1obSRuDF9ZRmrYtOnXUuFOM9YoFdbav7dTOOgPxHnoWwtAzX5pLCOooA==
REFRESH_JWT_SECRET: 6C4mM1Q4sHsxydgthxw_mAGVP_qNyv1obSRuDF9ZRmrYtOnXUuFOM9YoFdbav7dTOOgPxHnoWwtAzX5pLCOooA==
EXPIRES_IN: "5m"
REFRESH_JWT_EXPIRES_IN: "7d"