namespace: default
appName: ui
replicaCount: 1

image:
  repository: mahmudulazamshohan/ui
  tag: "0.1"

containerPort: 4003
servicePort: 80
protocalType: http

configMap:
  name: example-configmap-v3

serviceType: NodePort

ingressHost: localhost

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

MYSQL_HOST: db
MYSQL_PORT: 3306
MYSQL_USER: root
MYSQL_PASS: 123456
MYSQL_NAME: example_db
