namespace: default
appName: ui
replicaCount: 1

image:
  repository: mahmudulazamshohan/ui
  tag: "0.1"

PORT: 4003
NODE_ENV: production

AUTHENTICATION_UI: "authentication@http://localhost/api/authentication/static/remoteEntry.js"
FEED_UI: "feed@http://localhost/api/feed/static/remoteEntry.js"

configMap:
  name: example-configmap-v3
resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi