version: "3.8"
services:
  api-gateway:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    image: api-gateway
    container_name: api-gateway
    platform: linux/x86_64
    ports:
      - "80:80"
    depends_on:
      - authentication
      - feed
      - ui
    networks:
      - example-microservices

  authentication-db:
    platform: linux/x86_64
    image: mysql:8.0
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: authentication
      MYSQL_USER: user123456
      MYSQL_PASSWORD: 123456
    volumes:
      - "authentication-db:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - example-microservices

  feed-db:
    platform: linux/x86_64
    image: mysql:8.0
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feed
      MYSQL_USER: user123456
      MYSQL_PASSWORD: 123456
    volumes:
      - "feed-db:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - example-microservices

  rabbitmq:
    image: rabbitmq:3.9.28-management-alpine
    container_name: rabbitmq
    platform: linux/x86_64
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - example-microservices

  redis-cache:
    image: "redis:alpine"
    platform: linux/x86_64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - example-microservices

  redis-commander:
    container_name: redis-commander
    platform: linux/x86_64
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    build: .
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    ports:
      - "8081:8081"
    networks:
      - example-microservices

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8090:8080" # Jenkins Web UI
      - "50000:50000" # Agent communication
    volumes:
      - jenkins-data:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: 123456
    networks:
      - example-microservices

volumes:
  db:
    driver:
      local
  redis_data:
  jenkins-data: