
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  label:
    app: {{ .Values.appName }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
           - configMapRef:
               name: {{ .Values.configMap.name }}
          resources:
            requests:
              memory: "16Mi" 
              cpu: "50m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
