
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  label:
    app: {{ .Values.appName }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}

    spec:
      containers:
        - name: {{ .Values.appName }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.PORT }}
          env:
           - name: MYSQL_HOST
             value: "{{ .Values.MYSQL_HOST }}"
           - name: MYSQL_PORT
             value: "{{ .Values.MYSQL_PORT }}"
           - name: MYSQL_USER
             value: "{{ .Values.MYSQL_USER }}"
           - name: MYSQL_PASS
             value: "{{ .Values.MYSQL_PASS }}"
           - name: MYSQL_NAME
             value: "{{ .Values.MYSQL_NAME }}"
           - name: PORT
             value: "{{ .Values.PORT }}"
           - name: NODE_ENV
             value: "{{ .Values.NODE_ENV }}"
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
