name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Git
        run: git fetch --depth=2 # Fetch at least two commits for comparison

      - name: Get shortened Git commit SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image for authentication
        uses: docker/build-push-action@v5
        with:
          context: ./authentication
          file: ./authentication/authentication.dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/authentication:${{ github.ref_name }}-${{ env.SHORT_SHA }}

      - name: Build and push Docker image for feed
        uses: docker/build-push-action@v5
        with:
          context: ./feed
          file: ./feed/feed.dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/feed:${{ github.ref_name }}-${{ env.SHORT_SHA }}

      - name: Build and push Docker image for ui
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/ui.dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ui:${{ github.ref_name }}-${{ env.SHORT_SHA }}

      - name: Log out of Docker Hub
        run: docker logout
